apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller
  newName: quay.io/vpavlin/katib-controller
  newTag: openshift
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui
  newName: quay.io/vpavlin/katib-ui
  newTag: openshift
